# SPDX-FileCopyrightText: 2016-2017, Nefeli Networks, Inc.
# SPDX-FileCopyrightText: 2017, The Regents of the University of California.
# SPDX-FileCopyrightText: 2024, Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

- hosts: all
  tags: build-dep
  tasks:
    - name: Install APT prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - g++
          - make
          - libunwind8-dev
          - liblzma-dev
          - zlib1g-dev
          - libpcap-dev
          - libssl-dev
          - libnuma-dev
          - libgflags-dev
          - libgoogle-glog-dev
          - libgtest-dev
          - python3
          - python3-apt
          - python3-pyelftools
          - python3-setuptools
          - python3-pip
          - meson
          - ninja-build
          - pkg-config
        update_cache: yes
      become: true

    - name: Install gRPC and its requirements (apt)
      apt:
        name:
          - libc-ares-dev
          - libbenchmark-dev
          - libgrpc++-dev
          - libprotobuf-dev
          - protobuf-compiler-grpc
      become: true

    - name: BESS build dependencies installed
      debug:
        msg: "You are now ready to build BESS using build.py"
