# SPDX-FileCopyrightText: 2026 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

# CNDP (Cloud Native Data Plane) installation

- hosts: all
  tags: cndp
  tasks:
    - name: Install CNDP build dependencies
      apt:
        name:
          - libelf-dev
          - libbsd-dev
          - libjson-c-dev
          - libnl-3-dev
          - libnl-cli-3-dev
          - libnuma-dev
          - libpcap-dev
          - libbpf-dev
          - llvm
          - llvm-dev
          - libclang-dev
          - clang
          - lld
          - linux-libc-dev
          - gcc-multilib
          - m4
          - meson
          - pkg-config
          - wget
          - git
          - ca-certificates
          - build-essential
          - curl
          - xdp-tools
          - libxdp-dev
        update_cache: yes
      become: true

    - name: Install CNDP
      become: true
      block:
        - name: Clone CNDP repository
          git:
            repo: https://github.com/CloudNativeDataPlane/cndp.git
            dest: /tmp/cndp
            version: v24.07.0
            depth: 1

        - name: Build and install CNDP with meson
          shell: |
            cd /tmp/cndp
            meson setup builddir \
              --buildtype=release \
              -Dmachine=haswell \
              -Ddefault_library=both
            meson compile -C builddir -j$(nproc)
            meson install -C builddir
          args:
            creates: /usr/local/lib/x86_64-linux-gnu/libcndp.so

        - name: Check if Go is installed
          command: which go
          register: go_installed
          changed_when: false
          failed_when: false

        - name: Build prometheus-metrics app (skipped when golang is not installed)
          shell: |
            cd /tmp/cndp/lang/go/stats/prometheus
            go build -o /usr/local/bin/prometheus prometheus.go
          args:
            creates: /usr/local/bin/prometheus
          when: go_installed.rc == 0

        - name: Run ldconfig after CNDP installation
          shell: ldconfig

        - name: Remove CNDP source
          file:
            path: /tmp/cndp
            state: absent

    - name: CNDP installation complete
      debug:
        msg: "CNDP installation complete"
